### ISSUE TITLE
Android Compilation Error

### ISSUE THREAD

**Issue by guy-shahine** [shimohq/react-native-cookie#16]
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-cookie'.
      > Failed to notify project evaluation listener.
         > com.android.build.gradle.tasks.factory.AndroidJavaCompile.setDependencyCacheDir(Ljava/io/File;)V

Any ideas?

**Comment by chlela** [comment]
I fiddled with project and now I get

**Comment by KuoKongQingYun** [comment]
```
cd android
./gradlew clean
```
and then
```
cd ..
react-native run-android
```

**Comment by chlela** [comment]
Now I'm getting an error that minimum buildTools required is 25.0.0

**Comment by guy-shahine** [comment]
Awesome thank you. I'll close the ticket
