### ISSUE TITLE
Build error for iOS Info.plist not found

### ISSUE THREAD

**Issue by sja1n** [shimohq/react-native-cookie#18]
Hi, while using it for ios i get following build error

> ** BUILD FAILED **
> 
> 
> The following commands produced analyzer issues:
> 
> 	Analyze Base/RCTModuleMethod.mm normal x86_64
> (1 command with analyzer issues)
> 
> The following build commands failed:
> 	ProcessInfoPlistFile /Users/user/Documents/app/ios/build/Build/Products/Debug-iphonesimulator/RNCookieManagerTests.xctest/Info.plist RNCookieManagerTests/Info.plist
> (1 failure)
> 
> Installing build/Build/Products/Debug-iphonesimulator/MYAPP.app
> An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
> Failed to install the requested application
> An application bundle was not found at the provided path.
> Provide a valid path to the desired application bundle.
> Print: Entry, ":CFBundleIdentifier", Does Not Exist

Looks like Info.plist is required but not found in the project, is it something I have to create for this library specifically ?

**Comment by yusufyildirim** [comment]
* Select your target -> Build Phases -> Link Binary With Libraries -> Remove libRNCookieManagerTest.a
* Clean Project -> Build -> Good to go

**Comment by sja1n** [comment]
This solved the issue, Thanks
